/* This file was generated by syncqt. */
#ifndef QT_QTGAMEPAD_VERSION_H
#define QT_QTGAMEPAD_VERSION_H

#define QTGAMEPAD_VERSION_STR "5.12.6"

#define QTGAMEPAD_VERSION 0x050C06

#endif // QT_QTGAMEPAD_VERSION_H
