/* This file was generated by syncqt. */
#ifndef QT_QTCANVAS3D_VERSION_H
#define QT_QTCANVAS3D_VERSION_H

#define QTCANVAS3D_VERSION_STR "5.12.5"

#define QTCANVAS3D_VERSION 0x050C05

#endif // QT_QTCANVAS3D_VERSION_H
